# Nombres exactos de los paquetes de modelos .pkl que el pipeline espera.
# Los paths NO viven acá: consultar core/config.py (MODELS_DIR, METRICS_PATH).
SUPPORTED_MODELS: tuple[str, ...] = (
    "gradient_boosting",
    "logistic_regression",
    "multinomial_naive_bayes",
    "neural_network",
    "random_forest",
    "support_vector_machine_(linear_kernel)",
    "xgboost",
)

# Categorías canónicas que emite el backend; el frontend las traduce a UI.
CATEGORY_BULLYING: str = "Bullying"
CATEGORY_NOT_BULLYING: str = "Not Bullying"

# --- Normalización: expansión de contracciones ---
CONTRACTIONS: dict[str, str] = {
    "don't": "do not",
    "dont": "do not",
    "can't": "cannot",
    "cant": "cannot",
    "won't": "will not",
    "wont": "will not",
    "isn't": "is not",
    "isnt": "is not",
    "aren't": "are not",
    "arent": "are not",
    "didn't": "did not",
    "didnt": "did not",
    "doesn't": "does not",
    "doesnt": "does not",
    "wasn't": "was not",
    "wasnt": "was not",
    "weren't": "were not",
    "werent": "were not",
    "haven't": "have not",
    "havent": "have not",
    "hasn't": "has not",
    "hasnt": "has not",
    "hadn't": "had not",
    "hadnt": "had not",
    "i'm": "i am",
    "i've": "i have",
    "i'll": "i will",
    "you're": "you are",
    "you've": "you have",
    "we're": "we are",
    "they're": "they are",
    "it's": "it is",
    "that's": "that is",
    "what's": "what is",
    "there's": "there is",
}

# Slang de redes sociales -> forma canónica (u = you, idk = i do not know...)
SLANG: dict[str, str] = {
    # Pronombres/verbos abreviados
    "u": "you",
    "ur": "your",
    "r": "are",
    "n": "and",
    "y": "why",
    "k": "ok",
    "ya": "you",
    "yall": "you all",
    # Contracciones
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "lemme": "let me",
    "gimme": "give me",
    "imma": "i am going to",
    "kinda": "kind of",
    "sorta": "sort of",
    "dunno": "do not know",
    # Abreviaturas
    "idk": "i do not know",
    "idc": "i do not care",
    "ngl": "not going to lie",
    "tbh": "to be honest",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "smh": "shake my head",
    "btw": "by the way",
    "rn": "right now",
    "fr": "for real",
    "af": "as fuck",
    "afk": "away from keyboard",
    "bc": "because",
    "cuz": "because",
    "bcoz": "because",
    "cos": "because",
    "tho": "though",
    "pls": "please",
    "plz": "please",
    "thx": "thanks",
    "wut": "what",
    "wat": "what",
    "sup": "what is up",
    "lol": "laugh out loud",
    "omg": "oh my god",
    "brb": "be right back",
    # Chatspeak
    "aint": "are not",
    "da": "the",
    "dat": "that",
    "dis": "this",
    "dem": "them",
    "dese": "these",
    "dose": "those",
    "dey": "they",
    "dere": "there",
    "kno": "know",
    "luv": "love",
    "gud": "good",
    "wuz": "was",
    "wus": "was",
    "pic": "picture",
    "pics": "pictures",
    "cmon": "come on",
    "hbu": "how about you",
}

# Leetspeak (b4 = before, h8 = hate)
LEET: dict[str, str] = {
    "b4": "before",
    "2day": "today",
    "2nite": "tonight",
    "2night": "tonight",
    "2mrrw": "tomorrow",
    "2morrow": "tomorrow",
    "2mrw": "tomorrow",
    "2morw": "tomorrow",
    "str8": "straight",
    "str8p": "straight",
    "some1": "someone",
    "sum1": "someone",
    "any1": "anyone",
    "no1": "no one",
    "every1": "everyone",
    "h8": "hate",
    "4got": "forgot",
    "gr8": "great",
    "in2": "into",
    "2getha": "together",
    "2gether": "together",
    "2do": "to do",
    "2b": "to be",
    "4ever": "forever",
    "2much": "too much",
    "4da": "for the",
    "l8r": "later",
    "m8": "mate",
    "w8": "wait",
    "4u": "for you",
    "2u": "to you",
    "2go": "to go",
    "2me": "to me",
    "4me": "for me",
    "2know": "to know",
    "2see": "to see",
    "2have": "to have",
    "2make": "to make",
    "2give": "to give",
    "2stop": "to stop",
    "2come": "to come",
    "2show": "to show",
    "2bully": "to bully",
    "n00b": "noob",
    "bl00d": "blood",
    "bl00dy": "bloody",
    "br00t4l": "brutal",
    "r4pe": "rape",
    "k1ll3d": "killed",
    "sh00ter": "shooter",
    "f4ggots": "faggots",
    "b1tch": "bitch",
    "h4te": "hate",
    "l0ve": "love",
    "f4il": "fail",
    "s0": "so",
}

# Palabras de negación; se conservan aunque spaCy las considere stopwords.
NEGATION_WORDS: frozenset[str] = frozenset(
    {"no", "not", "never", "nobody", "nothing", "nowhere", "neither", "nor", "cannot"}
)
